### ISSUE TITLE
Unable to hot reload the application

### ISSUE THREAD

**Issue by davidortinau** [adospace/reactorui-maui#10]
Followed the readme with net7 and Android. Same on Mac Catalyst. Using macOS Ventura and VS Code.

```
dmo@Davids-M1 my-new-project % dotnet-maui-reactor -f net7.0-android
MauiReactor Hot-Reload CLI
Version 1.0.72.0
Press Ctrl+C or Ctrl+Break to quit
Setting up build pipeline for my-new-project project...done.
Monitoring folder '/Users/dmo/work/my-new-project'...
Detected changes to 'Pages/MainPage.cs'
Replacing syntax tree for: Pages/MainPage.cs
Connecting to Hot-Reload server (Port: 45820)...Unable to hot reload the application:
System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
   at MauiReactor.HotReloadConsole.HotReloadClient.SendAssemblyFileToServer(MemoryStream stream, MemoryStream pdbStream, CancellationToken cancellationToken) in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 299
   at MauiReactor.HotReloadConsole.HotReloadClient.ConnectionLoop(CancellationToken cancellationToken) in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 156
```

**Comment by adospace** [comment]
David, in addition, you need the adb tool installed on your mac:

To check if it exists:
`adb devices `

To install:
Install the [homebrew](http://brew.sh/) package manager
` /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

Install adb
` brew install android-platform-tools`

I've just updated the documentation, let me know if it still doesn't work for you.

**Comment by davidortinau** [comment]
Thanks. This wasn't part of my template, and that seems to have been the missing bit.

```
#if DEBUG
.EnableMauiReactorHotReload()
#endif
```
