### ISSUE TITLE
HotReload Not Work With Android 

### ISSUE THREAD

**Issue by Ali1Jamal** [adospace/reactorui-maui#233]
Hello,
i just started new project using MauiReactor template using DotNet 8.0, I use macOS with apple silicon chip and rider ide, after make simple change like change text of lable the hot reload give me this error. in the terminal:
```
Detected changes to 'Pages/MainPage.cs'
Replacing syntax tree for: Pages/MainPage.cs
Connecting to Hot-Reload server (Port: 45820)...Unable to hot reload the application:
System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
   at MauiReactor.HotReloadConsole.HotReloadClient.SendAssemblyFileToServer(MemoryStream stream, MemoryStream pdbStream, CancellationToken cancellationToken) in D:\a\reactorui-maui\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 297
   at MauiReactor.HotReloadConsole.HotReloadClient.ConnectionLoop(CancellationToken cancellationToken) in D:\a\reactorui-maui\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 154

```
I try to run on real android device and emulator but the hot reload didn't wok with them ,
I try hot reload with maccatalyst its works but not work with android.
my package reference is:
```
    <ItemGroup>
        <PackageReference Include="Reactor.Maui" Version="2.0.*"/>
        <PackageReference Include="Reactor.Maui.Canvas" Version="2.0.*"/>
        <PackageReference Include="Reactor.Maui.ScaffoldGenerator" Version="2.0.15-beta" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
```

**Comment by adospace** [comment]
Hi,
not related to the issue, ScaffoldGenerator is no longer required after beta releases:
```c#
    <ItemGroup>
        <PackageReference Include="Reactor.Maui" Version="2.0.*"/>
        <PackageReference Include="Reactor.Maui.Canvas" Version="2.0.*"/>
    </ItemGroup>
```
