### ISSUE TITLE
No Connection to Hot-Reload Server (Port: 45820)

### ISSUE THREAD

**Issue by itschnie** [adospace/reactorui-maui#234]
**Describe the bug**
When I use "dotnet-maui-reactor -f net8.0-android" and make changes to the code, I get an error message that I cannot connect to port 45820. Changes are therefore not applied.

**To Reproduce**
0. open PowerShell
1. dotnet new install Reactor.Maui.TemplatePack
2. dotnet tool install -g Reactor.Maui.HotReload
3. dotnet new maui-reactor-startup -o maurec1
4. cd .\marec1\
5. command ". code"
6. open VSCode (also tried with Visual Studio 2022)
7. execute the command: "dotnet build -t:Run -f net8.0-android"
8. the app is created and successfully opened in the Android Simulator
9. open another CMD shell and enter: "dotnet-maui-reactor -f net8.0-android"
10. the following error message appears when I make changes to the code:
"""
Connection to the hot reload server (port: 45820)...Hot reload of the application not possible:
System.Net.Sockets.SocketException (10061): A connection could not be established because the target computer rejected the connection.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
at MauiReactor.HotReloadConsole.HotReloadClient.SendAssemblyFileToServer(MemoryStream stream, MemoryStream pdbStream, CancellationToken cancellationToken) in D:\a\reactorui-maui\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 297
   at MauiReactor.HotReloadConsole.HotReloadClient.ConnectionLoop(CancellationToken cancellationToken) in D:\a\reactorui-maui\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 154
"""

**Expected behavior**
I had expected changes in the code to be applied without an error message

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Smartphone (please complete the following information):**
 - Device: Android Simulator - Pixel_3a_API_34_extension_level_7_x86_64
 - Version : Android 14

**Comment by adospace** [comment]
Hi, 
MauiReactor hot reload is based on adb, can you execute the command "adb" in a shell and see what it returns? in case it says that it can't find the command you have to install it.

https://stackoverflow.com/questions/35854238/where-is-adb-exe-in-windows-10-located

https://developer-docs.magicleap.cloud/docs/guides/developer-tools/android-debug-bridge/adb-setup/#:~:text=Check%20for%20Existing%20ADB%20Installations,that%20lists%20your%20operating%20system.

https://www.xda-developers.com/install-adb-windows-macos-linux/

**Comment by MoDao1990217** [comment]
> 嗨，MauiReactor 热重载是基于 adb 的，你能在 shell 中执行命令“adb”看看它返回什么吗？如果它说它找不到命令，你必须安装它。
> 
> https://stackoverflow.com/questions/35854238/where-is-adb-exe-in-windows-10-located
> 
> https://developer-docs.magicleap.cloud/docs/guides/developer-tools/android-debug-bridge/adb-setup/#:~:text=Check%20for%20Existing%20ADB%20Installations,that%20lists%20your%20operating%20system。
> 
> https://www.xda-developers.com/install-adb-windows-macos-linux/

 @adospace  Hi, can it be used in production environment? I've been watching. I haven't used it yet.

**Comment by adospace** [comment]
Hum, I think that the problem is definitively related to adb.
Let's check a few things:
1) the application should be executed in Debug mode (I think you already did it)
2) Ensure that EnableMauiReactorHotReload() is called in your program.cs (I think you already have it)
3) Ensure that you have only one emulator/device running (i.e. if the device is attached, close the emulator and vice-versa)
4) The waiting for debugger message is normal and not related to MauiReactor (you should see the same with any other .NET MAUI app)
5) Ensure you have the platform-tools installed, the adb used by MauiReactor hot-reload must be in this folder:

C:\Program Files (x86)\Android\android-sdk\platform-tools

![image](https://github.com/adospace/reactorui-maui/assets/10573253/f3a0a21b-96e2-4d04-bdf2-cc2d225f63d9)

![image](https://github.com/adospace/reactorui-maui/assets/10573253/667b850c-3dc2-432c-b171-26ae5f6d7753)


Platform tools can be installed also from google:
https://developer.android.com/tools/releases/platform-tools

or installing Android Studio

hope it helps, let me know

**Comment by adospace** [comment]
@MoDao1990217 sorry not sure I correctly understand what you mean, yes MauiReactor can be used in a production environment

**Comment by adospace** [comment]
@itschnie any news?

**Comment by itschnie** [comment]
> @itschnie any news?

sorry for the late reply, i've been struggling a bit with illness and work.

I have downloaded the files and placed them in the folder you suggested (C:\Program Files (x86)\Android\android-sdk\platform-tools).

Unfortunately, the error persists.
![grafik](https://github.com/adospace/reactorui-maui/assets/73386340/544d6133-ba26-4098-a944-cac8876bf293)


Android Studio is already installed.
![grafik](https://github.com/adospace/reactorui-maui/assets/73386340/d638df71-f865-4401-80c4-8c3f58e5794f)

**Comment by itschnie** [comment]
Update: Maybe i solved the "Connection Problem".

I've tried:
I seem to have solved the problem.

> Open Console
> adb kill-server
> adb start-server
> dotnet build -t:Run -f net8.0-android
> dotnet-maui-reactor -f net8.0-android

That was the sequence I used. I will try it again later and hope it was the solution to the problem.
![grafik](https://github.com/adospace/reactorui-maui/assets/73386340/97c93e11-fd34-4858-b195-f944a380f1ee)

**Comment by adospace** [comment]
yes messages are correct, seems working
