### ISSUE TITLE
Hot-reload error when running on ios simulator

### ISSUE THREAD

**Issue by LITTOMA** [adospace/reactorui-maui#24]
The hot reload program tried to load the dll at `my-new-project/bin/Debug/net7.0-ios/my-new-project.dll`, however the actual build output is `my-new-project/bin/Debug/net7.0-ios/iossimulator-x64/my-new-project.dll`

**Comment by adospace** [comment]
hum, not sure what `/iossimulator-x64/` is? did you change the output directory? can you post the error you received if any?

**Comment by LITTOMA** [comment]
I haven't changed the output folder.

I got this output:

```
Detected changes to 'Pages/MainPage.cs'
MSBuild version 17.4.0+18d5aef85 for .NET
  Detected signing identity:
          
    Bundle Id: com.companyname.my_new_project
    App Id: com.companyname.my_new_project
  my-new-project -> /<removed>/my-new-project/bin/Debug/net7.0-ios/iossimulator-x64/my-new-project.dll
  优化程序集以调整大小可能会更改应用的行为。请务必在发布后进行测试。请参阅: https://aka.ms/dotnet-illink
  正在优化程序集以调整大小。此过程可能需要一段时间。

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:04.44

Unable to hot reload the application:
System.IO.FileNotFoundException: Could not find file '/<removed>/my-new-project/bin/Debug/net7.0-ios/my-new-project.dll'.
File name: '/<removed>/my-new-project/bin/Debug/net7.0-ios/my-new-project.dll'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at MauiReactor.HotReloadConsole.HotReloadClientFull.CompileProject(Stream stream, Stream pdbStream, CancellationToken cancellationToken) in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClientFull.cs:line 53
   at MauiReactor.HotReloadConsole.HotReloadClient.ConnectionLoop(CancellationToken cancellationToken) in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 151

```

**Comment by adospace** [comment]
hum, yes the path to the DLL is correct to me, did you build the project first? I'm not sure you see the DLL under `/iossimulator-x64/`

**Comment by LITTOMA** [comment]
Yes I followed the documentation and successfully built the project using the command:
`dotnet build -t:Run /p:_DeviceName=:v2:udid=<device_id> -f net7.0-ios`

All build outputs are found under `/iossimulator-x64/`.

**Comment by adospace** [comment]
ok, I see, can you show the command you use to run the hot-reload?

**Comment by LITTOMA** [comment]
I was using this
`dotnet-maui-reactor -f net7.0-ios --mode Full`

**Comment by adospace** [comment]
ok, do you have the latest version of the tool? can you upgrade to the latest version of the tool with: `dotnet tool install -g Reactor.Maui.HotReload --prerelease`

**Comment by LITTOMA** [comment]
I found a workaround by adding `-o bin/Debug/net7.0-ios` to the build command.
So the command now would be:
```
dotnet build -t:Run /p:_DeviceName=:v2:udid=<device_id> -f net7.0-ios -o bin/Debug/net7.0-ios
```

**Comment by adospace** [comment]
I tried to repro this issue without luck, for now, I'll close it
