### ISSUE TITLE
MauiReactor 3 - ArgumentNullException on GetRequiredService

### ISSUE THREAD

**Issue by afriscic** [adospace/reactorui-maui#264]
Hello.
Tried to update one app to v3 today but got this exception at this line:
`Services.GetRequiredService<SerializationScan.Services.DbService>();`
Exception thrown: 'System.ArgumentNullException' in Microsoft.Extensions.DependencyInjection.Abstractions.dll: 'Value cannot be null.'

MauiProgram.cs:
```
...
builder.Services.AddSingleton<DbService>();
return builder.Build();
```

AppShell.cs:
```
public partial class AppShell : Component
{
    [Inject]
    private readonly DbService dbService;
...
}
```

and I get the generated file:
```
// <auto-generated />
using Microsoft.Extensions.DependencyInjection;

#nullable enable
namespace SerializationScan
{
    partial class AppShell
    {
        public AppShell()
        {
            dbService = Services.GetRequiredService<SerializationScan.Services.DbService>();
        }
    }
}
```

**Comment by adospace** [comment]
hum, looking, anyway what is strange is that the NRE is raised by the Microsoft.Extensions.DependencyInjection.Abstractions.dll.

can you post the complete stack trace?

**Comment by afriscic** [comment]
```
Exception has occurred: CLR/System.ArgumentNullException
Exception thrown: 'System.ArgumentNullException' in Microsoft.Extensions.DependencyInjection.Abstractions.dll: 'Value cannot be null.'
   at System.ThrowHelper.Throw(String paramName)
   at System.ThrowHelper.ThrowIfNull(Object argument, String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at SerializationScan.AppShell..ctor() in /Users/afriscic/Projects/SerializationScan2/SerializationScan/obj/Debug/net9.0-android/MauiReactor.ScaffoldGenerator/MauiReactor.ScaffoldGenerator.ComponentPartialClassSourceGenerator/AppShell.g.cs:line 13
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, IntPtr* args, Exception& exc)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at MauiReactor.ReactorApplicationHost`1.Run()
   at MauiReactor.ReactorApplication`1.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState)
   at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
```

**Comment by afriscic** [comment]
This is from a "upgraded" working .NET 8 project. Haven't tried to create a new test project.

**Comment by adospace** [comment]
can you confirm that you're using XAML resources and initializing the application with a code like this?
```c#
public partial class App : MauiReactorApplication
{
    public App()
    {
        InitializeComponent();
    }
}


public abstract class MauiReactorApplication : ReactorApplication<HomePage>
{
    public MauiReactorApplication()
    {
        this.UseTheme<ApplicationTheme>();
    }
}

```

**Comment by afriscic** [comment]
App.xaml.cs
```
using MauiReactor;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Maui.Controls;
using SerializationScan.Resources.Styles;
using SerializationScan.Services;

namespace SerializationScan;

public partial class App : MauiReactorApplication
{
    public App()
    {
        InitializeComponent();
    }
}


public abstract class MauiReactorApplication : ReactorApplication<AppShell>
{
    public MauiReactorApplication()
    {
        this.UseTheme<AppTheme>();
    }
}
```

App.xaml
```
<?xml version = "1.0" encoding = "UTF-8" ?>
<local:MauiReactorApplication xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:SerializationScan"
             x:Class="SerializationScan.App">
    <local:MauiReactorApplication.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Resources/Styles/Colors.xaml" />
                <ResourceDictionary Source="Resources/Styles/Styles.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </local:MauiReactorApplication.Resources>
</local:MauiReactorApplication>
```

`AppTheme.cs` is a copy from your test project. `Colors.xaml` and `Styles.xaml `are from my .NET 8 project.

**Comment by afriscic** [comment]
Works with 3.0.3

Thank you for awesome work!
