### ISSUE TITLE
Can't start Hot Reload console

### ISSUE THREAD

**Issue by teejay-87** [adospace/reactorui-maui#4]
I'm trying to use MauiReactor, I just setup the test project.

It compiles fine and I'm running it on the iOS simulator with the following command:

`dotnet build -t:Run /p:_DeviceName=:v2:udid=979A827D-CDC4-4FE4-8244-EA31AB9201AF -f net6.0-ios``

The UDID is needed to start iPhone 13 Pro simulator, otherwise iPad Air 5 was starting (didn't know the background logic of this...)

Anyway, when running, the application starts fine in the simulator but the command doesn't exit... so, I can't launch `dotnet-maui-reactor`, not in the current console at least.

I tried to open a new macOS terminal and run `dotnet-maui-reactor` but with no luck:

```teejay$ dotnet-maui-reactor
MauiReactor Hot-Reload CLI
Version 1.0.52.0
Press Ctrl+C or Ctrl+Break to quit
Setting up build pipeline for my-new-project project...done.
Unhandled exception. System.InvalidOperationException: StandardOut has not been redirected or the process hasn't started yet.
   at System.Diagnostics.Process.get_StandardOutput()
   at MauiReactor.HotReloadConsole.HotReloadClient.ExecutePortForwardCommmand() in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 372
   at MauiReactor.HotReloadConsole.HotReloadClient.Run(CancellationToken cancellationToken) in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\HotReloadClient.cs:line 107
   at MauiReactor.HotReloadConsole.Program.RunMonitorAndConnectionClient(Options options) in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\Program.cs:line 42
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at MauiReactor.HotReloadConsole.Program.Main(String[] args) in C:\projects\reactorui-maui\src\MauiReactor.HotReloadConsole\Program.cs:line 20
   at MauiReactor.HotReloadConsole.Program.<Main>(String[] args)
Abort trap: 6```

**Comment by adospace** [comment]
Yes, definitely there is a problem with the hot-reload on Mac for iOS apps, working on that.
Back soon as I've a fix, do you have problems in hot reload Android apps?

**Comment by teejay-87** [comment]
Didn't tried with Android Emulator. Will try.

**Comment by adospace** [comment]
Yes, anyway, looking at the code you should get the same error for Android too...

**Comment by adospace** [comment]
This issue should be fixed using the latest version of the hot-reload command:
`dotnet tool update -g Reactor.Maui.HotReload --prerelease`

I've recorded a small screencast here: https://screencast-o-matic.com/watch/c3jwXKVTGYo 

Please re-open the issue if it's still not working for you, thanks
